// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjxUrmyVZ-XHM_FP-qBpxamZtX5qCrAsg',
    appId: '1:648540767599:web:ac6852156ccfd94375949a',
    messagingSenderId: '648540767599',
    projectId: 'spor-uygulama-4ddf2',
    authDomain: 'spor-uygulama-4ddf2.firebaseapp.com',
    databaseURL: 'https://spor-uygulama-4ddf2-default-rtdb.firebaseio.com',
    storageBucket: 'spor-uygulama-4ddf2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFpThZGe5CMDEZhhkQcRfL0rrsb-dyjus',
    appId: '1:648540767599:android:aed5cc42b45bfa6175949a',
    messagingSenderId: '648540767599',
    projectId: 'spor-uygulama-4ddf2',
    databaseURL: 'https://spor-uygulama-4ddf2-default-rtdb.firebaseio.com',
    storageBucket: 'spor-uygulama-4ddf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4XvV-wRe0gJMEW4_n95ieIeWoFfQT20Q',
    appId: '1:648540767599:ios:c097be2be25605c775949a',
    messagingSenderId: '648540767599',
    projectId: 'spor-uygulama-4ddf2',
    databaseURL: 'https://spor-uygulama-4ddf2-default-rtdb.firebaseio.com',
    storageBucket: 'spor-uygulama-4ddf2.firebasestorage.app',
    iosBundleId: 'com.example.sporUygulama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4XvV-wRe0gJMEW4_n95ieIeWoFfQT20Q',
    appId: '1:648540767599:ios:c097be2be25605c775949a',
    messagingSenderId: '648540767599',
    projectId: 'spor-uygulama-4ddf2',
    databaseURL: 'https://spor-uygulama-4ddf2-default-rtdb.firebaseio.com',
    storageBucket: 'spor-uygulama-4ddf2.firebasestorage.app',
    iosBundleId: 'com.example.sporUygulama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjxUrmyVZ-XHM_FP-qBpxamZtX5qCrAsg',
    appId: '1:648540767599:web:bbd73e2538d90bba75949a',
    messagingSenderId: '648540767599',
    projectId: 'spor-uygulama-4ddf2',
    authDomain: 'spor-uygulama-4ddf2.firebaseapp.com',
    databaseURL: 'https://spor-uygulama-4ddf2-default-rtdb.firebaseio.com',
    storageBucket: 'spor-uygulama-4ddf2.firebasestorage.app',
  );

}